### ISSUE TITLE
同一个 pvc 绑定在 Pod 不同路径上，导致 pod 长时间处于 ContainerCreating 状态

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#27]
使用模板创建 jupyterbook 不成功，一直在转圈

错误原因是下面的 YAML：

```
          volumeMounts:
            - name: workingdir
              mountPath: /t9k/mnt
            - name: datadir-1
              mountPath: /t9k/export
      volumes:
        - name: workingdir
          persistentVolumeClaim:
            claimName: pvc-demo
        - name: datadir-1
          persistentVolumeClaim:
            claimName: pvc-demo
```

同一个 PVC 添加两次应该报错。
