### ISSUE TITLE
端口管理策略

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#48]
1. 如何进行端口的开放和关闭。（容器内）
2. 如何指定某个容器可以使用对外端口。
3. 现在的容器对外网的访问，实现的方式是什么。
4. 能否支持某个容器单独对外进行端口开放。

**Comment by wd0011** [comment]
![image](https://user-images.githubusercontent.com/34251317/232743812-4e9684cc-872e-486c-9d2a-38d112e84d46.png)
我这张图上的理解是否正确？

**Comment by ppkube** [comment]
> 我这张图上的理解是否正确？

这个都是 ”集群内部“ 的网络，并不是对外的。

@shenkejie15 : 我们提供一个完整的包含 Ingress 的 例子 ；也解释一下 NodePort 类型的 `Service` 之使用

**Comment by shenkejie15** [comment]
## 示例

[Ingress](https://kubernetes.io/zh-cn/docs/concepts/services-networking/ingress/) 是对集群中服务的外部访问进行管理的 API 对象。

IBMC 集群中已经部署了 Ingress 控制器 [ingress-nginx](https://kubernetes.github.io/ingress-nginx/deploy/)，并部署了默认的 Ingress 类 `nginx`。因此可以直接创建 Ingress 资源来使用。

我们提供一个简单的例子来说明 Ingress 资源的使用。首先准备文件 `http-echo.yaml`，其内容如下：

``` YAML
apiVersion: v1
kind: Pod
metadata:
  name: http-echo
  labels:
    app.kubernetes.io/name: http-echo
spec:
  containers:
  - name: hello-world
    image: t9kpublic/http-echo
    args:
      - -text="hello world"
    ports:
      - containerPort: 5678
        name: http-web-svc
    resources:
        limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: http-echo
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```

指定一个项目，部署 Pod 和 Service：

``` shell
k -n <project> apply -f http-echo.yaml
```

从集群内（比如同个项目的 Notebook 中），我们可以使用下面方式访问 Service：

``` shell
# 查看 Service 信息
$ k get service http-echo
NAME        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
http-echo   ClusterIP   10.233.17.185   <none>        80/TCP    6m58s

# 从集群内通过 Service 访问
$ curl 10.233.17.185
"hello world"
```

创建 Ingress 暴露服务：

``` shell
cat << EOF | k -n <project> create -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: http-echo
            port:
              number: 80
EOF
```

从集群外访问服务：

``` shell
$ curl -H "Host: foo.bar.com" http://<ingress-host-IP>
"hello world"
```

这里的 `<ingress-host-IP>` 是部署了 Ingress 控制器的节点 IP 地址。

## 补充说明

Service 具有不同[类型](https://kubernetes.io/zh-cn/docs/concepts/services-networking/service/#publishing-services-service-types)。上文使用的是 `ClusterIP` 类型的 Service，它通过集群的内部 IP 暴露服务，因此只能从集群内部访问。`NodePort` 类型的 Service 通过集群中每个节点上的 IP 和静态端口暴露服务，比如下面的 Service：

``` shell
$ k get service
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
http-echo                     NodePort    10.233.17.185   <none>        80:31959/TCP      42m
```

可以通过如下方式访问服务：
``` shell
$ curl -H "Host: foo.bar.com" http://<any-host-IP>:31959
"hello world"
```

这里的 `<any-host-IP>` 可以是 Kubernetes 集群中任意节点的 IP 地址。
