### ISSUE TITLE
环境加载速度异常慢

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#60]
**bug 描述**
环境加载速度异常慢（包括python和R），比如一个包导入可能需要10分钟甚至更久。

**复现方法**
TODO

在一个基础的 notebook 中未能复现该问题：
![image](https://github.com/t9k/user-support/assets/48315992/f7082391-d51c-4f91-9a0b-a9ff200d43bf)

**期望的行为（可选）**
应当在较短时间内完成环境加载操作

**环境（可选）**
 - 平台版本：1.75.0

**额外的上下文信息（可选）**
已经确认：
1. 出现问题的 Notebook 本身剩余资源充足
2. 出现问题的 Notebook 所在节点的剩余资源充足

**Comment by shenkejie15** [comment]
**复现方法**

1. 创建一个包含 conda 的 Notebook（例如使用 “registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/miniconda-22.11.1-notebook:1.72.0-sudo” 镜像），其中 `/t9k/mnt` 挂载一个 tsz-cephfs 类型的 PVC。测试使用的 YAML 见附录。
2. 运行 `conda create --prefix /t9k/mnt/myenv python=3.10`，创建 Python 环境并保存在 `/t9k/mnt/myenv` 中
3. 激活 conda 环境，`conda activate /t9k/mnt/myenv`
4. 安装一个 python 包，这里以 `pandas` 为例，`pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas`
5. 重启 Notebook（暂停 Notebook，然后恢复）
6. 激活 conda 环境，`conda activate /t9k/mnt/myenv`
7. 装载 python 包，`time python3 -c "import pandas as pd"`，查看装载速度。本次装载耗时 43.6 秒，远超预期。

**附录**
1. 测试结果附图：
![image](https://github.com/t9k/user-support/assets/48315992/06b3c674-1c22-45c5-92ea-20235a4206a8)

补充说明，此时不仅是装载 package，运行任何 Python 命令的耗时均长于预期。

2. Notebook 完整的 YAML：
```
apiVersion: tensorstack.dev/v1beta1
kind: Notebook
metadata:
  name: s3-pvc-test
  namespace: demo
spec:
  runMode: running
  scheduler:
    t9kScheduler:
      queue: default
  ssh:
    authorized_keys:
    - skj-ssh-key
    enabled: true
    serviceType: ClusterIP
  template:
    spec:
      containers:
      - command: []
        image: registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/miniconda-22.11.1-notebook:1.72.0-sudo
        name: notebook
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
        volumeMounts:
        - mountPath: /t9k/mnt
          name: workingdir
        - mountPath: /t9k/s3
          name: datadir-1
      volumes:
      - name: workingdir
        persistentVolumeClaim:
          claimName: test-skj
      - name: datadir-1
        persistentVolumeClaim:
          claimName: skjtest
  type: jupyter
```
